<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Scrap;
use App\Form\MediaType;
use App\Service\ScrapperService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Panther\Client;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\Asset\Package;
use Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy;
use XLSXReader\XLSXReader;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use App\Service\GeneratorService;
use Symfony\Component\HttpFoundation\StreamedResponse;


class ScrapperController extends AbstractController
{

     private $scrapperService;
     public $generatorService;
    /**
     * @Route("/scrapper", name="app_scrapper_index")
     */
    public function new(Request $request , ScrapperService $scrapperService , GeneratorService $generatorService)
    {

       /*
        $data =   $this->scrapper($scrapperService );
        var_dump($data);
        $extension = substr($data->getImage(),-4);
        $imageName= $this->generateUniqueFileName() .$extension;
        var_dump($imageName);
        file_put_contents($this->getParameter('upload_directory'). '/'.$imageName, fopen($data->getImage(), 'r'));
        */


        $media = new Media();
        $form = $this->createForm(MediaType::class, $media);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file


                var_dump($media);
            die();
            return  $this->scrapper($data,$media->getName(),$scrapperService , $generatorService);

            die();
        }

        return $this->render('scrapper/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }




    public function scrapper(ScrapperService $scrapperService )
    {


        $data= $scrapperService->scrapPage('http://voursa.com/Annoncev.cfm?pdtid=131335&payee=2&adtre=NSSAN%20TD%2042');

                //$data = $this->scrapPage();
       // echo $data;
            return $data;

    }




    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }




}

