<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mUslXqe' shared service.

return $this->privates['.service_locator.mUslXqe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'generatorService' => ['privates', 'App\\Service\\GeneratorService', 'getGeneratorServiceService.php', true],
    'scrapperService' => ['privates', 'App\\Service\\ScrapperService', 'getScrapperServiceService.php', true],
]);
