<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ScrapperController::generateCsvAction' => ['privates', '.service_locator.9elK94A', 'get_ServiceLocator_9elK94AService.php', true],
    'App\\Controller\\ScrapperController::new' => ['privates', '.service_locator.HHhqW9.', 'get_ServiceLocator_HHhqW9_Service.php', true],
    'App\\Controller\\ScrapperController:generateCsvAction' => ['privates', '.service_locator.9elK94A', 'get_ServiceLocator_9elK94AService.php', true],
    'App\\Controller\\ScrapperController:new' => ['privates', '.service_locator.HHhqW9.', 'get_ServiceLocator_HHhqW9_Service.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
