<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\GeneratorService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/GeneratorService.php';

return $this->privates['App\\Service\\GeneratorService'] = new \App\Service\GeneratorService();
